# Generated by Django 2.2.12 on 2020-07-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpcuaServerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_id', models.CharField(max_length=50)),
                ('server_name', models.CharField(max_length=100)),
                ('endpoint_url', models.CharField(max_length=200)),
                ('server_description', models.CharField(max_length=500)),
            ],
        ),
    ]
